#!/usr/bin/env php
<?php

use Packedge\Workbench\Foundation\EventManager;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
    require __DIR__.'/vendor/autoload.php';
}
else
{
    require __DIR__.'/../../autoload.php';
}

// Stolen from https://github.com/laravel/homestead/blob/master/homestead
function workbench_path()
{
    if (isset($_SERVER['HOME']))
    {
        return $_SERVER['HOME'].'/.workbench';
    }
    else
    {
        return $_SERVER['HOMEDRIVE'].$_SERVER['HOMEPATH'].DIRECTORY_SEPARATOR.'.workbench';
    }
}

$manager = new EventManager;
$manager->listen('package.new', 'Packedge\Workbench\Listeners\NewPackageListener' );

$app = new Application('Packedge Workbench', '0.2.0');
$app->add(new \Packedge\Workbench\Console\Package\NewCommand($manager));
$app->run();